RESTROREC/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Reco import views as rviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', rviews.showModels, name='showModels'),
    # path('', views.showRecommendation, name='showRecommendation'),
    path('', include('Reco.urls')),
    path('register', rviews.registerView, name='registerView'),
    path('login', rviews.loginView, name='loginView'),
    path('logout/',rviews.logoutView,name='logoutView'),
    path('home/<str:pid>',rviews.errorview,name='errorview'),
    path('', rviews.showModels, name='showModels'),
]

Reco/urls.py
from django.conf.urls import url
from django.urls.resolvers import URLPattern
from . import views
from django.urls import path
from django.contrib import admin
app_name = 'Reco'
urlpatterns = [
    path('restaurant', views.showRest, name='showRest'),
    path('Menu', views.showMenu, name='showMenu'),
    path('profile', views.profileView, name='profileView'),
    path('Order', views.orderView, name='orderView'),
    path('Rate', views.rateView, name='rateView'),
]

templates/chooseModel.html
{% extends "sitebase.html" %}
{% block title %}
  <title>Home</title>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<br> <br>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <h3 class="h1 whiteh1"> Welcome to RESTROREC! </h3>
            <h3 class="whiteh3"> Choose a Recommendation Model </h3>
            <form class="form-group" action="{% url 'showModels' %}" method="POST">
                {% csrf_token %}
                <div class="select">
                <select name="model" id="model" class="mySelectArrow" style="width: 50rem;">

                    <option value=1>Recommendations based on chosen menu item.</option>
                    <option value=2>Recommendations based on your profile and chosen menu item.</option>
                    <option value=3>Recommendations based on your profile and order history.</option>

                </select>
            </div>
                <button class="btn btn-primary btn-block" type="submit" style="width: 12rem; margin-top: 1rem;">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/display.html
{% extends "sitebase.html" %}
{% block title %}
  <title>Recommended Items</title>
{% endblock %}
{% block content %}
<br> <br>
<div class="container">
    <!-- <h3> Logged in as User.username </h3> -->
    <h3 class="whiteh3"> Our recommendations for you:</h3>
    <div>
        <form class="form-group" action="{% url 'Reco:orderView' %}" method="POST">
            {% csrf_token %}
            <div class="tablecontainer">
                <div class="rowhead">
                    <div class="sitem">Select
                    </div>
                    <div class="litem">Item Name
                    </div>
                    <div class="mitem">Cuisine
                    </div>
                    <div class="sitem">Price
                    </div>
                    <div class="mitem">Restaurant
                    </div>
                    <div class="sitem">Rating
                    </div>
                    <div class="litem">Address
                    </div>
            </div>
        {% for t in dishes %}
            <div class="rowcontainer">
                <div class="sitem"><input type="checkbox" name="order" value="{{t.7}}" id="{{t.7}}" class="checkbo">
                </div>
                <div class="litem"><label for="{{t.7}}">{{t.0}}</label>
                </div>
                <div class="mitem">{{t.5}}
                </div>
                <div class="sitem">{{t.2}}
                </div>
                <div class="mitem">{{t.3}}
                </div>
                <div class="sitem">{{t.8}}
                </div>
                <div class="litem">{{t.6}}
                </div>
            </div>
        {% endfor %}
    </div>
        <button class="btn btn-primary btn-block" type="submit" style="width: 12rem; margin: 1rem 0 0 0.5rem; " >Rate Recommendations</button>
        </form>
        
    </div>
</div>  
{% endblock %}

templates/error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">


	<title >Error</title>


	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'assets/css/error.css' %}">

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>{{ e }}</h2>
			</div>
			<a href="{%url 'loginView' %}">Go To Login Page</a>
		</div>
	</div>

</body>

</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<title>Login </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/icons/site.webmanifest' %}">
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="container-login100-form-btn" >
                <button class="login100-form-btn" style="width: 10%; margin-bottom: 1rem; background-color: black;">
                    <a href="{%url 'showModels' %}">Home</a>
                </button>
            </div>
			
			<div class="wrap-login100">
				<span class="login100-form-title page-title">
					Login to RESTROREC
				</span>
				<div class="login100-pic js-tilt" data-tilt>
					
					<img src="{% static 'images/indianfood.jpg' %}" alt="IMG">
					
				</div>


				<form class="login100-form login100-form1 validate-form" action="{% url 'loginView' %}" method="POST">
					{% csrf_token %}


                    {% if m is not None %}
                <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>

				{{ m }}

			    </div>
                {% else %}
                
                {% endif %}

					
					<span class="login100-form-title">
						Login
					</span>
				
					<div class="wrap-input100 validate-input" data-validate="Username is required">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" value="Login">
							Login
						</button>
					</div>
					<div class="text-center p-t-136">
						<a class="txt2" href="{%url 'registerView' %}">
							<h3>Go to Sign Up page</h3>
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
				
			</div>
		</div>
	</div>
	<script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'assets/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/main.html
{% extends "sitebase.html" %}
{% block title %}
  <title>Restaurants</title>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<br> <br>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <h3 class="whiteh3"> Choose a Restaurant </h3>
            <form class="form-group" action="{% url 'Reco:showRest' %}" method="POST">
                {% csrf_token %}
                <select name="restaurant" id="select_restaurant" class="mySelectArrow" style="width: 20rem;">
                    {% for t in rest %}
                    <option value={{t.restaurantId}}>{{t.name}}</option>
                    {% endfor %}
                </select>
                <input type="hidden" id="model" name="model" value="{{m}}">
                <button class="btn btn-primary btn-block" type="submit" style="width: 12rem; margin-top: 1rem;">Submit</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/main2.html
{% extends "sitebase.html" %}
{% block title %}
  <title>Home</title>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<br> <br>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <h3 class="whiteh3"> Choose a Menu Item to get similar recommendations</h3>
            <form class="form-group" action="{% url 'Reco:showMenu' %}" method="POST">
                {% csrf_token %}
                <select name="selected_item" id="selected_item" class="mySelectArrow" style="width: 20rem;">
                    {% for t in menu %}
                    <option value={{t.itemId}}>{{t.name}}</option>
                    {% endfor %}
                </select>
                <input type="hidden" id="model" name="model" value="{{m}}">
                <button class="btn btn-primary btn-block" type="submit" style="width: 12rem; margin-top: 1rem;" >Submit</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/myprofile.html
{% extends "sitebase.html" %}
{% block title %}
  <title>My Profile</title>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<br> <br>
<div class="container">
    <h3 class="whiteh3"> My Profile </h3>
    <div class="card ">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Name: {{User.name}}</li>
          <li class="list-group-item">Diet: {{User.diet}}</li>
          <li class="list-group-item">Preferred Flavour: {{User.flavour}}</li>
          <li class="list-group-item">Preferred Ingredients: {{User.ingredient}} </li>
          <li class="list-group-item">Region: {{User.region}}</li>
          <li class="list-group-item">State: {{User.state}}</li>
          <li class="list-group-item">Current Satisfaction Level (1-5): {{sat}}</li>
        </ul>
      </div>
</div>

{% endblock %}

templates/rateFood.html
{% extends "sitebase.html" %}
{% block title %}
  <title>Rate Items</title>
{% endblock %}
{% block content %}
<br> <br>
<div class="container">
    <!-- <h3> Logged in as User.username </h3> -->
    <h3 class="whiteh3">Rate Your Order </h3>
    <div>
        <form class="form-group" action="{% url 'Reco:rateView' %}" method="POST">
            {% csrf_token %}

        <div class="tablecontainer">
            <div class="rowhead">
                <div class="mitem">Item Name
                </div>
                <div class="mitem">Price(INR)
                </div>
                <div class="mitem">Restaurant
                </div>
                <div class="mitem">Rating
                </div>
        </div>
    {% for t in orders %}
        <div class="rowcontainer">
            <div class="mitem">{{t.0}}
            </div>
            <div class="mitem">{{t.1}}
            </div>
            <div class="mitem">{{t.2}}
            </div>
            <div class="mitem"><input type="number" step="1" min="1" max="5" name="ratings" id="{{t.3}}" multiple>
            </div>
            <input type="hidden" id="{{t.3}}" name="ids" value="{{t.3}}" multiple>
        </div>
    {% endfor %}
</div>
        <button class="btn btn-primary btn-block" type="submit" style="width: 12rem; margin: 1rem 0 0 0.5rem; " >Submit Ratings</button>
        </form>
        
    </div>
</div>  
{% endblock %}

templates/register.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <title>Register</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/icons/site.webmanifest' %}">

</head>

<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="container-login100-form-btn" >
                <button class="login100-form-btn" style="width: 10%; margin-bottom: 1rem; background-color: black;">
                    <a href="{%url 'showModels' %}">Home</a>
                </button>
            </div>
            <div class="wrap-login100">
                <span class="login100-form-title page-title">
					Create your profile
				</span>
                <form class="login100-form login100-form2 validate-form" action="{% url 'registerView' %}" method="POST">
                    {% csrf_token %}
                    {{formA|crispy}}
                    {{formB|crispy}}
                    <div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" value="Login">
							Sign Up
						</button>
					</div>
                </form>
            </div>
        </div>
    </div>




    <script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
	<script src="{% static 'assets/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

        

templates/sitebase.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% block title %}

      {% endblock %}


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css">

    <style>
    @font-face{
    font-family:MyFont; 
    src: url(../../static/assets/fonts/Raleway-VariableFont_wght.ttf)
    }
    @font-face {
      font-family: Poppins-Regular;
      src: url("../../static/assets/fonts/poppins/Poppins-Regular.ttf");
    }

    @font-face {
      font-family: Poppins-Bold;
      src: url("../../static/assets/fonts/poppins/Poppins-Bold.ttf");
    }

    @font-face {
      font-family: Poppins-Medium;
      src: url("../../static/assets/fonts/poppins/Poppins-Medium.ttf");
    }

    @font-face {
      font-family: Montserrat-Bold;
      src: url("../../static/assets/fonts/montserrat/Montserrat-Bold.ttf");
    }


    .row{
        padding: 5px;
    }
    .fa-tint{     
        color: red;    
    }
    .blood{
        float: right;
    }
    .fa-users{     
        color: blue; 
        font-size: 3ex;   
    }
    .fa-spinner{     
        color: blue; 
        font-size: 3ex;   
    }
    .fa-check-circle{     
        color: blue; 
        font-size: 3ex;   
    }
    .xyz{     
        color: blue; 
        font-size: 3ex;   
    }

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  list-style: none;
  text-decoration: none;
  font-family: 'Josefin Sans', sans-serif;
}

body{
  font-family: Poppins-Regular, sans-serif;
  background-image: url(../../static/images/img5.png);
  background-color: #f3f5f9;
  background-size:cover;
  position: relative;
}
body .bgi{
   /* background-color: #f3f5f9; */
  background-size:cover;
  position: relative;
}

.bg-danger {
    background-color: #ff0018!important;
}
.whiteh3{
  font-family: Poppins-Regular, sans-serif;
  color: white;
  padding-bottom: 1em;
  font-weight: bolder;
}
.whiteh1{
  font-family: MyFont, sans-serif;
  color: white;
  padding-bottom: 2em;
  align-self: center;
}
select.mySelectArrow{
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    background: #2596be;
    color: #fff;
    width: 100%;
    padding: 10px 20px;
    font-size: 22px;
}
select.mySelectArrow option {
    color: #000;
    padding: 0 10px;
}
.select:after {
    content: '\25BC';
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    font-size: 25px;
    border: 1px solid #565656;
    background: #0e7b53;
    color: #fff;
    padding: 11px 15px;
    pointer-events: none;
}
.select {
    position: relative;
    width: 800px;
}

.tablecontainer{
  width: 100%;
  height: 100%;
  display: flex;
  flex-flow: column wrap;
  justify-content: center;
  align-items: center;
  background-color: #daeae6;
}
.rowcontainer{
  font-family: 'Raleway',MyFont;
  width: 100%;
  height: 4em;
  display: flex;
  justify-content: space-around;
  align-items: center;
  background-color:#dfdfdf ;
  padding: 0.2em;
  flex-basis:auto;
  vertical-align: middle;
  border-radius: 10px;
}
.rowhead{
  font-family: 'Raleway',MyFont;
  font-size: 1.1em;
  font-weight: bold;
  width: 100%;
  height: 3.5em;
  display: flex;
  justify-content: space-around;
  align-items: center;
  background-color:#2596be;
  padding: 0.2em;
  flex-basis:auto;;
}
.sitem{
  font-family: 'Raleway',MyFont;
  width: 7%;
  height: 100%;
  display: flex;
  justify-content: left;
  align-items: center;
  flex-basis:auto;
  flex-grow: 4;
  margin: 0.50em;
  vertical-align: middle;
}
.mitem{
  font-family: 'Raleway',MyFont;
  width: 18%;
  height: 100%;
  display: flex;
  justify-content: left;
  align-items: center;
  flex-basis:auto;
  flex-grow: 4;
  margin: 0.50em;
  vertical-align: middle;
}
.litem{
  font-family: 'Raleway',MyFont;
  width: 25%;
  height: 100%;
  display: flex;
  justify-content: left;
  align-items: center;
  flex-basis:auto;
  flex-grow: 4;
  margin: 0.50em;
  vertical-align: middle;
}
.checkbo{
  width: 1.5em;
  height: 1.5em;
}
.card{
  border-radius: 10px;
}
.limiter {
  width: 100%;
  margin: 0 auto;
}

.container-login100 {
  width: 100%;
  min-height: 100vh;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  padding: 15px;
}
.wrap-login100 {
  width: 1000px;
  background: #343a40;
  border-radius: 10px;
  overflow: hidden;
  color: white;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  padding: 100px 130px 33px 95px;
}
.wrapper{
  display: flex;
  position: relative;
}

.wrapper .sidebar{
  width: 200px;
  height: 100%;
  background: 	#343a40;
  padding: 30px 0px;
  position: fixed;
}

.wrapper .sidebar h2{
  color: #fff;
  text-transform: uppercase;
  text-align: center;
  margin-bottom: 30px;
}

.wrapper .sidebar ul li{
  padding: 15px;
  border-bottom: 1px solid #bdb8d7;
  border-bottom: 1px solid rgba(0,0,0,0.05);
  border-top: 1px solid rgba(255,255,255,0.05);
}    

.wrapper .sidebar ul li a{
  color: #bdb8d7;
  display: block;
}

.wrapper .sidebar ul li a .fas{
  width: 25px;
}

.wrapper .sidebar ul li:hover{
  background-color: #594f8d;
}
    
.wrapper .sidebar ul li:hover a{
  color: #fff;
}
 
.wrapper .sidebar .social_media{
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
}

.wrapper .sidebar .social_media a{
  display: block;
  width: 40px;
  background: #594f8d;
  height: 40px;
  line-height: 45px;
  text-align: center;
  margin: 0 5px;
  color: #bdb8d7;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.wrapper .main_content{
  width: 100%;
  margin-left: 200px;
}

.wrapper .main_content .header{
  padding: 20px;
  background: #fff;
  color: #717171;
  border-bottom: 1px solid #e0e4e8;
}

.wrapper .main_content .info{
  margin: 20px;
  color: #717171;
  line-height: 25px;
}

.wrapper .main_content .info div{
  margin-bottom: 20px;
}

@media (max-height: 500px){
  .social_media{
    display: none !important;
  }
}
.fa-sign-out-alt{
    color: white;
    font-size: 2ex;
}
  .label {
     color: white;
     padding: 8px;
   }
   
   .success {background-color: #4CAF50;} /* Green */
   .info {background-color: #2196F3;} /* Blue */
   .warning {background-color: #ff9800;} /* Orange */
   .danger {background-color: #f44336;} /* Red */
   .other {background-color: #e7e7e7; color: black;} /* Gray */

</style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-dark">
        <a style="color:white;" class="navbar-brand" href="/"><i class="fab fa-cutlery"></i>&nbsp;<font face = "Comic sans MS" size ="4">RESTROREC</font></a>
        
      
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" style="color: white;" href="{%url 'Reco:profileView' %}">View Profile &nbsp; <i class="fas fa-user"></i></a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="{%url 'logoutView' %}">Logout &nbsp; <i class="fas fa-sign-out-alt"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="color: white;" href="{%url 'showModels' %}">Home <i class="fas fa-home"></i></a>
              </li>
                
            </ul>
        </div>
      </nav>
    <br><br>

    <div class="main_content">
      {% block content %}

      {% endblock %}
    </div>

    </div>



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>